// Browser only (WebCrypto). Never imports the plaintext roster.
//
// Decrypts exactly one certificate record from the static blob
// (public/certificate-data.json, generated by
// scripts/build-certificate-blobs.mjs). Every failure — unknown NIM,
// corrupt blob, fetch error, bad payload — throws the same generic error
// so callers cannot distinguish "NIM not in set" from other failures.

import type { StudentCertificate } from "@/data/certificates/types";

// Must match scripts/build-certificate-blobs.mjs.
const ITERATIONS = 100_000;
const BLOB_URL = "/certificate-data.json";

// Single generic message for all lookup failures — no oracle.
const GENERIC_ERROR = "Certificate not found";

let blobPromise: Promise<Record<string, { salt: string; iv: string; data: string }>> | null =
  null;

function bytesToHex(bytes: ArrayBuffer): string {
  return [...new Uint8Array(bytes)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
}

async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return bytesToHex(digest);
}

function loadBlob(): Promise<Record<string, { salt: string; iv: string; data: string }>> {
  if (!blobPromise) {
    blobPromise = (async () => {
      try {
        const res = await fetch(BLOB_URL);
        if (!res.ok) throw new Error(GENERIC_ERROR);
        const blob = (await res.json()) as Record<
          string,
          { salt: string; iv: string; data: string }
        >;
        if (!blob || typeof blob !== "object") throw new Error(GENERIC_ERROR);
        return blob;
      } catch {
        // Reset so a transient network failure can be retried, but still
        // surface the same generic message.
        blobPromise = null;
        throw new Error(GENERIC_ERROR);
      }
    })();
  }
  return blobPromise;
}

function isValidRecord(record: unknown): record is StudentCertificate {
  if (!record || typeof record !== "object") return false;
  const r = record as Record<string, unknown>;
  return (
    typeof r.name === "string" &&
    typeof r.nim === "string" &&
    typeof r.division === "string" &&
    typeof r.team_name === "string" &&
    Array.isArray(r.certificates) &&
    r.certificates.every(
      (c) =>
        !!c &&
        typeof c === "object" &&
        typeof (c as Record<string, unknown>).title === "string" &&
        typeof (c as Record<string, unknown>).drive_link === "string",
    )
  );
}

export async function lookupCertificate(nim: string): Promise<StudentCertificate> {
  try {
    const normalized = nim.trim();
    if (!normalized) throw new Error(GENERIC_ERROR);

    const blob = await loadBlob();
    const entry = blob[await sha256Hex(normalized)];
    if (!entry || !entry.salt || !entry.iv || !entry.data) {
      throw new Error(GENERIC_ERROR);
    }

    const passwordKey = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(normalized),
      "PBKDF2",
      false,
      ["deriveBits"],
    );
    const keyBits = await crypto.subtle.deriveBits(
      {
        name: "PBKDF2",
        hash: "SHA-256",
        salt: base64ToBytes(entry.salt).buffer as ArrayBuffer,
        iterations: ITERATIONS,
      },
      passwordKey,
      256,
    );
    const aesKey = await crypto.subtle.importKey("raw", keyBits, "AES-GCM", false, [
      "decrypt",
    ]);
    const plaintext = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: base64ToBytes(entry.iv).buffer as ArrayBuffer },
      aesKey,
      base64ToBytes(entry.data).buffer as ArrayBuffer,
    );
    const record = JSON.parse(new TextDecoder().decode(plaintext)) as unknown;
    if (!isValidRecord(record)) throw new Error(GENERIC_ERROR);
    return record;
  } catch {
    throw new Error(GENERIC_ERROR);
  }
}
